//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba4_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public int ClassID { get; set; }
        public Nullable<System.DateTime> ClassDate { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> TrainerID { get; set; }
    
        public virtual Members Members { get; set; }
        public virtual Trainers Trainers { get; set; }
    }
}
